COUNTRY_CODE_TO_LOCATION_NAME = {
    "AR": "ARGENTINA",
    "BO": "BOLIVIA",
    "BR": "BRAZIL",
    "CL": "CHILE",
    "CO": "COLOMBIA",
    "CR": "COSTA RICA",
    "DO": "DOMINICAN REPUBLIC",
    "EC": "ECUADOR",
    "GF": "FRENCH GUIANA",
    "GT": "GUATEMALA",
    "HN": "HONDURAS",
    "MQ": "MARTINIQUE",
    "MX": "MEXICO",
    "NI": "NICARAGUA",
    "PA": "PANAMA",
    "PE": "PERU",
    "PR": "PUERTO RICO",
    "UY": "URUGUAY",
    "US": "UNITED STATES",
    "VE": "VENEZUELA",
}