from typing import Any, Dict

FIELD_MAPPINGS: Dict[str, Dict[str, Dict[str, Any]]] = {
    "beetle_species": {
        "beetle_id": {"type": "id", "classes": ["gueltig"]},
        "taxon_id": {"type": "quality", "classes": ["vorhanden", "fehlend"]},
        "family": {"type": "taxonomy", "classes": ["familie"]},
        "genus": {"type": "taxonomy", "classes": ["gattung"]},
        "specific_epithet": {"type": "taxonomy", "classes": ["epitheton"]},
        "scientific_name": {"type": "taxonomy", "classes": ["artname"]},
        "scientific_name_authorship": {"type": "taxonomy", "classes": ["autorenschaft"]},
    },
    "location": {
        "location_id": {"type": "id", "classes": ["gueltig"]},
        "latitude": {"type": "geo", "classes": ["sued", "nord"]},
        "longitude": {"type": "geo", "classes": ["west", "ost"]},
        "coordinate_uncertainty": {
            "type": "band",
            "classes": ["hochpraezise", "moderat", "unscharf", "sehr_unscharf", "nicht_numerisch", "unbekannt"],
        },
        "country": {"type": "admin", "classes": ["land"]},
        "region": {"type": "admin", "classes": ["region"]},
        "city": {"type": "admin", "classes": ["stadt"]},
        "verbatim_locality": {"type": "text", "classes": ["vorhanden", "fehlend"]},
        "elevation": {"type": "band", "classes": ["low", "mid", "high", "veryHigh"]},
        "slope": {"type": "band", "classes": ["level", "gentle", "moderate", "steep", "very_steep", "unknown"]},
        "landcover_class": {
            "type": "band",
            "classes": ["tree_cover", "shrubland", "grassland", "cropland", "built_up", "bare_sparse", "snow_ice", "water", "wetland", "mangroves", "moss_lichen", "unknown"],
        },
        "soil_ph": {"type": "band", "classes": ["strongly_acidic", "acidic", "neutral", "alkaline", "strongly_alkaline", "unknown"]},
        "soil_organic_carbon": {"type": "band", "classes": ["very_low_carbon", "low_carbon", "moderate_carbon", "high_carbon", "very_high_carbon", "unknown"]},
        "worldclim_bio01": {"type": "band", "classes": ["cold", "mild", "warm", "hot", "unknown"]},
        "worldclim_bio12": {"type": "band", "classes": ["arid", "semi_arid", "sub_humid", "humid", "per_humid", "unknown"]},
        "distance_to_water_m": {"type": "band", "classes": ["riparian", "near_water", "intermediate_distance", "inland", "far_inland", "unknown"]},
        "ecoregion_id": {"type": "quality", "classes": ["vorhanden", "fehlend"]},
        "biome_id": {"type": "quality", "classes": ["vorhanden", "fehlend"]},
        "human_modification": {"type": "band", "classes": ["natural", "low_modification", "moderate_modification", "high_modification", "unknown"]},
    },
    "observation": {
        "gbif_id": {"type": "id", "classes": ["gueltig"]},
        "recorded_by": {"type": "text", "classes": ["vorhanden", "fehlend"]},
        "catalogue_number": {"type": "text", "classes": ["vorhanden", "fehlend"]},
        "identification_id": {"type": "text", "classes": ["vorhanden", "fehlend"]},
        "identified_by": {"type": "text", "classes": ["vorhanden", "fehlend"]},
        "beetle_id": {"type": "id", "classes": ["gueltig"]},
        "taxon_id": {"type": "quality", "classes": ["vorhanden", "fehlend"]},
        "location_id": {"type": "id", "classes": ["gueltig"]},
        "event_date": {"type": "band", "classes": ["vollstaendig", "jahr_monat", "nur_jahr", "frei_text", "fehlend"]},
        "verbatim_event_date": {"type": "text", "classes": ["vorhanden", "fehlend"]},
        "basis_of_record": {"type": "quality", "classes": ["vorhanden", "fehlend"]},
        "dataset_name": {"type": "quality", "classes": ["vorhanden", "fehlend"]},
        "institution_code": {"type": "quality", "classes": ["vorhanden", "fehlend"]},
        "image_available": {"type": "flag", "classes": ["mit_bild", "ohne_bild"]},
    },
    "media": {
        "media_id": {"type": "id", "classes": ["gueltig"]},
        "gbif_id": {"type": "id", "classes": ["gueltig"]},
        "image_url": {"type": "quality", "classes": ["vorhanden", "fehlend"]},
        "references": {"type": "text", "classes": ["vorhanden", "fehlend"]},
        "creator": {"type": "text", "classes": ["vorhanden", "fehlend"]},
        "publisher": {"type": "text", "classes": ["vorhanden", "fehlend"]},
        "rights_holder": {"type": "text", "classes": ["vorhanden", "fehlend"]},
        "license": {"type": "quality", "classes": ["offen", "unklar_oder_restriktiv", "fehlend"]},
    },
    "climate_snapshot": {
        "climate_id": {"type": "id", "classes": ["gueltig"]},
        "location_id": {"type": "id", "classes": ["gueltig"]},
        "snapshot_date": {"type": "time", "classes": ["monatssnapshot"]},
        "avg_temperature": {"type": "band", "classes": ["cold", "mild", "warm", "hot", "unknown"]},
        "precipitation": {"type": "band", "classes": ["arid", "semi_arid", "sub_humid", "humid", "per_humid", "unknown"]},
        "soil_moisture": {"type": "band", "classes": ["very_dry", "dry", "moist", "wet", "unknown"]},
        "ndvi": {"type": "band", "classes": ["barren", "sparse_vegetation", "moderate_vegetation", "dense_vegetation", "unknown"]},
        "relative_humidity": {"type": "band", "classes": ["dry_air", "moderate_humidity", "humid_air", "very_humid_air", "unknown"]},
        "surface_pressure_hpa": {"type": "band", "classes": ["extreme_low_pressure", "very_low_pressure", "low_pressure", "normal_pressure", "high_pressure", "unknown"]},
        "nighttime_lights": {"type": "band", "classes": ["dark", "low_light", "moderate_light", "bright_light", "unknown"]},
    },
}
