services:
  BeetleAtlas:
    image: ghcr.io/petrixuser/beetleatlas:latest
    container_name: BeetleAtlas
    restart: unless-stopped
    networks:
      - nas-reverse-proxy
    environment:
      - GMAPS_KEY=${GMAPS_KEY}
      - API_BASE_URL=${API_BASE_URL:-}

networks:
  nas-reverse-proxy:
    external: true
