from typing import Dict, Optional

from fastapi import Query


def beetle_query_params(
    q: Optional[str] = Query(None, max_length=200),
    climate: Optional[str] = Query(None),
    vegetation: Optional[str] = Query(None),
    elevation: Optional[str] = Query(None, pattern="^(low|mid|high|veryHigh)$"),
    temperature_band: Optional[str] = Query(None),
    precipitation_band: Optional[str] = Query(None),
    soil_moisture_band: Optional[str] = Query(None),
    ndvi_band: Optional[str] = Query(None),
    humidity_band: Optional[str] = Query(None),
    pressure_band: Optional[str] = Query(None),
    light_pollution_band: Optional[str] = Query(None),
    slope_band: Optional[str] = Query(None),
    water_distance_band: Optional[str] = Query(None),
    human_impact_band: Optional[str] = Query(None),
    landcover_group: Optional[str] = Query(None),
    coordinate_uncertainty_band: Optional[str] = Query(None),
    soil_ph_band: Optional[str] = Query(None),
    soil_carbon_band: Optional[str] = Query(None),
    worldclim_temp_band: Optional[str] = Query(None),
    worldclim_precip_band: Optional[str] = Query(None),
    event_date_quality: Optional[str] = Query(None),
    basis_of_record_class: Optional[str] = Query(None),
    taxon_resolution: Optional[str] = Query(None),
    media_coverage: Optional[str] = Query(None),
    license_class: Optional[str] = Query(None),
    bbox: Optional[str] = Query(None),
    limit: int = Query(100, ge=1, le=50000),
    offset: int = Query(0, ge=0),
    sort_by: str = Query(
        "id",
        pattern="^(id|name|family|observedAt|elevation|temperature|climate|vegetation)$",
    ),
    sort_dir: str = Query("asc", pattern="^(asc|desc)$"),
) -> Dict[str, object]:
    return {
        "q": q,
        "climate": climate,
        "vegetation": vegetation,
        "elevation": elevation,
        "temperature_band": temperature_band,
        "precipitation_band": precipitation_band,
        "soil_moisture_band": soil_moisture_band,
        "ndvi_band": ndvi_band,
        "humidity_band": humidity_band,
        "pressure_band": pressure_band,
        "light_pollution_band": light_pollution_band,
        "slope_band": slope_band,
        "water_distance_band": water_distance_band,
        "human_impact_band": human_impact_band,
        "landcover_group": landcover_group,
        "coordinate_uncertainty_band": coordinate_uncertainty_band,
        "soil_ph_band": soil_ph_band,
        "soil_carbon_band": soil_carbon_band,
        "worldclim_temp_band": worldclim_temp_band,
        "worldclim_precip_band": worldclim_precip_band,
        "event_date_quality": event_date_quality,
        "basis_of_record_class": basis_of_record_class,
        "taxon_resolution": taxon_resolution,
        "media_coverage": media_coverage,
        "license_class": license_class,
        "bbox": bbox,
        "limit": limit,
        "offset": offset,
        "sort_by": sort_by,
        "sort_dir": sort_dir,
    }


def map_query_params(
    bbox: str = Query(...),
    zoom: int = Query(6, ge=0, le=24),
    q: Optional[str] = Query(None, max_length=200),
    climate: Optional[str] = Query(None),
    vegetation: Optional[str] = Query(None),
    elevation: Optional[str] = Query(None, pattern="^(low|mid|high|veryHigh)$"),
    temperature_band: Optional[str] = Query(None),
    precipitation_band: Optional[str] = Query(None),
    soil_moisture_band: Optional[str] = Query(None),
    ndvi_band: Optional[str] = Query(None),
    humidity_band: Optional[str] = Query(None),
    pressure_band: Optional[str] = Query(None),
    light_pollution_band: Optional[str] = Query(None),
    slope_band: Optional[str] = Query(None),
    water_distance_band: Optional[str] = Query(None),
    human_impact_band: Optional[str] = Query(None),
    landcover_group: Optional[str] = Query(None),
    coordinate_uncertainty_band: Optional[str] = Query(None),
    soil_ph_band: Optional[str] = Query(None),
    soil_carbon_band: Optional[str] = Query(None),
    worldclim_temp_band: Optional[str] = Query(None),
    worldclim_precip_band: Optional[str] = Query(None),
    event_date_quality: Optional[str] = Query(None),
    basis_of_record_class: Optional[str] = Query(None),
    taxon_resolution: Optional[str] = Query(None),
    media_coverage: Optional[str] = Query(None),
    license_class: Optional[str] = Query(None),
    limit: int = Query(500, ge=1, le=5000),
    offset: int = Query(0, ge=0),
    sort_by: str = Query(
        "speciesName",
        pattern="^(speciesName|observedAt|elevation|climate|vegetation)$",
    ),
    sort_dir: str = Query("asc", pattern="^(asc|desc)$"),
) -> Dict[str, object]:
    return {
        "bbox": bbox,
        "zoom": zoom,
        "q": q,
        "climate": climate,
        "vegetation": vegetation,
        "elevation": elevation,
        "temperature_band": temperature_band,
        "precipitation_band": precipitation_band,
        "soil_moisture_band": soil_moisture_band,
        "ndvi_band": ndvi_band,
        "humidity_band": humidity_band,
        "pressure_band": pressure_band,
        "light_pollution_band": light_pollution_band,
        "slope_band": slope_band,
        "water_distance_band": water_distance_band,
        "human_impact_band": human_impact_band,
        "landcover_group": landcover_group,
        "coordinate_uncertainty_band": coordinate_uncertainty_band,
        "soil_ph_band": soil_ph_band,
        "soil_carbon_band": soil_carbon_band,
        "worldclim_temp_band": worldclim_temp_band,
        "worldclim_precip_band": worldclim_precip_band,
        "event_date_quality": event_date_quality,
        "basis_of_record_class": basis_of_record_class,
        "taxon_resolution": taxon_resolution,
        "media_coverage": media_coverage,
        "license_class": license_class,
        "limit": limit,
        "offset": offset,
        "sort_by": sort_by,
        "sort_dir": sort_dir,
    }
