from typing import Any, Dict

FILTER_OPTIONS = {
    "climates": ["cold", "mild", "warm", "hot", "unknown"],
    "vegetations": [
        "tree_cover",
        "shrubland",
        "grassland",
        "cropland",
        "built_up",
        "bare_sparse",
        "snow_ice",
        "water",
        "wetland",
        "mangroves",
        "moss_lichen",
        "unknown",
    ],
    "elevations": ["low", "mid", "high", "veryHigh"],
    "temperatureBands": ["cold", "mild", "warm", "hot", "unknown"],
    "precipitationBands": ["arid", "semi_arid", "sub_humid", "humid", "per_humid", "unknown"],
    "soilMoistureBands": ["very_dry", "dry", "moist", "wet", "unknown"],
    "ndviBands": ["barren", "sparse_vegetation", "moderate_vegetation", "dense_vegetation", "unknown"],
    "humidityBands": ["dry_air", "moderate_humidity", "humid_air", "very_humid_air", "unknown"],
    "pressureBands": ["extreme_low_pressure", "very_low_pressure", "low_pressure", "normal_pressure", "high_pressure", "unknown"],
    "lightPollutionBands": ["dark", "low_light", "moderate_light", "bright_light", "unknown"],
    "slopeBands": ["level", "gentle", "moderate", "steep", "very_steep", "unknown"],
    "waterDistanceBands": ["riparian", "near_water", "intermediate_distance", "inland", "far_inland", "unknown"],
    "humanImpactBands": ["natural", "low_modification", "moderate_modification", "high_modification", "unknown"],
    "coordinateUncertaintyBands": ["hochpraezise", "moderat", "unscharf", "sehr_unscharf", "nicht_numerisch", "unbekannt"],
    "soilPhBands": ["strongly_acidic", "acidic", "neutral", "alkaline", "strongly_alkaline", "unknown"],
    "soilCarbonBands": ["very_low_carbon", "low_carbon", "moderate_carbon", "high_carbon", "very_high_carbon", "unknown"],
    "worldclimTempBands": ["cold", "mild", "warm", "hot", "unknown"],
    "worldclimPrecipBands": ["arid", "semi_arid", "sub_humid", "humid", "per_humid", "unknown"],
    "eventDateQualityBands": ["vollstaendig", "jahr_monat", "nur_jahr", "frei_text", "fehlend"],
    "basisOfRecordClasses": ["beobachtung", "sensor", "beleg", "probe", "sonstiges", "unbekannt"],
    "taxonResolutionClasses": ["artniveau", "gattungsniveau", "familienniveau", "unaufgeloest"],
    "mediaCoverageClasses": ["keine_bilder", "ein_bild", "mehrere_bilder", "viele_bilder"],
    "licenseClasses": ["offen", "unklar_oder_restriktiv", "fehlend"],
    "landcoverGroups": [
        "tree_cover",
        "shrubland",
        "grassland",
        "cropland",
        "built_up",
        "bare_sparse",
        "snow_ice",
        "water",
        "wetland",
        "mangroves",
        "moss_lichen",
        "unknown",
    ],
}


def to_beetle_payload(row: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "id": f"occ-{row['gbif_id']}",
        "name": row.get("name") or "Unbekannt",
        "family": row.get("family") or "Unbekannt",
        "location": row.get("location") or "Unbekannt",
        "coordinates": [
            float(row["lng"]) if row.get("lng") is not None else None,
            float(row["lat"]) if row.get("lat") is not None else None,
        ],
        "climate": row.get("climate") or "unknown",
        "vegetation": row.get("vegetation") or "unknown",
        "elevation": int(round(row["elevation"])) if row.get("elevation") is not None else 0,
        "temperature": float(row["temperature"]) if row.get("temperature") is not None else None,
        "soil": row.get("soil") or "unknown",
        "observedAt": row.get("observedAt"),
        "meta": {
            "observation": {
                "gbifId": row.get("gbif_id"),
                "eventDateQuality": row.get("event_date_quality") or "fehlend",
                "basisOfRecordClass": row.get("basis_of_record_class") or "unbekannt",
                "datasetName": row.get("dataset_name"),
                "institutionCode": row.get("institution_code"),
                "imageAvailable": bool(row.get("image_available", 0)),
            },
            "taxonomy": {
                "taxonId": row.get("taxon_id"),
                "genus": row.get("genus"),
                "specificEpithet": row.get("specific_epithet"),
                "resolution": row.get("taxon_resolution") or "unaufgeloest",
            },
            "location": {
                "country": row.get("country"),
                "region": row.get("region"),
                "city": row.get("city"),
                "coordinateUncertainty": row.get("coordinate_uncertainty"),
                "coordinateUncertaintyBand": row.get("coordinate_uncertainty_band") or "unbekannt",
                "soilPh": float(row["soil_ph"]) if row.get("soil_ph") is not None else None,
                "soilPhBand": row.get("soil_ph_band") or "unknown",
                "soilOrganicCarbon": float(row["soil_organic_carbon"]) if row.get("soil_organic_carbon") is not None else None,
                "soilCarbonBand": row.get("soil_carbon_band") or "unknown",
                "worldclimBio01": float(row["worldclim_bio01"]) if row.get("worldclim_bio01") is not None else None,
                "worldclimBio01Band": row.get("worldclim_temp_band") or "unknown",
                "worldclimBio12": float(row["worldclim_bio12"]) if row.get("worldclim_bio12") is not None else None,
                "worldclimBio12Band": row.get("worldclim_precip_band") or "unknown",
            },
            "media": {
                "mediaCount": int(row["media_count"]) if row.get("media_count") is not None else 0,
                "coverage": row.get("media_coverage") or "keine_bilder",
                "licenseSample": row.get("license_sample"),
                "licenseClass": row.get("license_class") or "fehlend",
            },
        },
        "ee": {
            "raw": {
                "precipitation": float(row["precipitation"]) if row.get("precipitation") is not None else None,
                "soilMoisture": float(row["soil_moisture"]) if row.get("soil_moisture") is not None else None,
                "ndvi": float(row["ndvi"]) if row.get("ndvi") is not None else None,
                "relativeHumidity": float(row["relative_humidity"]) if row.get("relative_humidity") is not None else None,
                "surfacePressureHpa": float(row["surface_pressure_hpa"]) if row.get("surface_pressure_hpa") is not None else None,
                "nighttimeLights": float(row["nighttime_lights"]) if row.get("nighttime_lights") is not None else None,
                "slope": float(row["slope"]) if row.get("slope") is not None else None,
                "distanceToWaterM": float(row["distance_to_water_m"]) if row.get("distance_to_water_m") is not None else None,
                "humanModification": float(row["human_modification"]) if row.get("human_modification") is not None else None,
                "landcoverClass": row.get("landcover_class"),
                "ecoregionId": row.get("ecoregion_id"),
                "biomeId": row.get("biome_id"),
            },
            "bands": {
                "temperature": row.get("temperature_band") or "unknown",
                "precipitation": row.get("precipitation_band") or "unknown",
                "soilMoisture": row.get("soil_moisture_band") or "unknown",
                "ndvi": row.get("ndvi_band") or "unknown",
                "humidity": row.get("humidity_band") or "unknown",
                "pressure": row.get("pressure_band") or "unknown",
                "lightPollution": row.get("light_pollution_band") or "unknown",
                "slope": row.get("slope_band") or "unknown",
                "waterDistance": row.get("water_distance_band") or "unknown",
                "humanImpact": row.get("human_modification_band") or "unknown",
                "landcoverGroup": row.get("landcover_group") or "unknown",
            },
        },
    }
